**Model 1**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import RFE
import statsmodels.api as sm
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_excel("C:/Users/akank/OneDrive/Desktop/BankingDataset.xlsx")
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,49,blue-collar,married,basic.9y,unknown,no,no,cellular,nov,wed,227,4,999,0,nonexistent,no
1,37,entrepreneur,married,university.degree,no,no,no,telephone,nov,wed,202,2,999,1,failure,no
2,78,retired,married,basic.4y,no,no,no,cellular,jul,mon,1148,1,999,0,nonexistent,yes
3,36,admin.,married,university.degree,no,yes,no,telephone,may,mon,120,2,999,0,nonexistent,no
4,59,retired,divorced,university.degree,no,no,no,cellular,jun,tue,368,2,999,0,nonexistent,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32945,28,services,single,high.school,no,yes,no,cellular,jul,tue,192,1,999,0,nonexistent,no
32946,52,technician,married,professional.course,no,yes,no,cellular,nov,fri,64,1,999,1,failure,no
32947,54,admin.,married,basic.9y,no,no,yes,cellular,jul,mon,131,4,999,0,nonexistent,no
32948,29,admin.,married,university.degree,no,no,no,telephone,may,fri,165,1,999,0,nonexistent,no
32949,35,admin.,married,university.degree,no,no,yes,telephone,jun,tue,544,3,999,0,nonexistent,no

In [3]:
ND = pd.get_dummies(df[['job', 'marital','education','default','housing','loan','contact','month','day_of_week','poutcome']], drop_first=True)
ND

,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32945,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
32946,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
32947,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
32948,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
32949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [4]:
a1 = df['y']
a2 = df['age']
a3 = df['duration']
a4 = df['campaign']
CD = pd.concat([a1,a2,a3,a4, ND], axis=1)

In [5]:
CD['y']  = CD['y'].replace('yes',1)
CD['y']  = CD['y'].replace('no',0)

In [6]:
y = CD['y']

In [7]:
CD.columns

Index(['y', 'age', 'duration', 'campaign', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student', 'job_technician',
       'job_unemployed', 'job_unknown', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.6y', 'education_basic.9y',
       'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown', 'default_unknown', 'default_yes',
       'housing_unknown', 'housing_yes', 'loan_unknown', 'loan_yes',
       'contact_telephone', 'month_aug', 'month_dec', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_nonexistent', 'poutcome_success'],
      dtype='object')

In [11]:
CD.to_csv('ModifiedData.csv')

In [8]:
x=CD.drop(['y','marital_married', 'marital_single',
       'marital_unknown','loan_unknown', 'loan_yes','campaign'], axis='columns')

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, train_size = .80)

In [10]:
l_reg = LogisticRegression()

In [11]:
l_reg.fit(x_train,y_train)

C:\Users\akank\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [12]:
prediction = l_reg.predict(x_test)
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
accuracy_score(y_test,prediction)*100

90.66767830045524

**Model 2**

In [17]:
x=CD.drop(['y','marital_married', 'marital_single',
       'marital_unknown','loan_unknown', 'loan_yes','campaign','housing_unknown', 'housing_yes','day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed','age'], axis='columns')

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, train_size = .80)

In [19]:
l_reg.fit(x_train,y_train)

C:\Users\akank\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
prediction = l_reg.predict(x_test)
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
accuracy_score(y_test,prediction)*100

90.59180576631259